# Generated by Django 4.0.6 on 2022-09-09 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_category_comments_auction_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_list',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
