# Generated by Django 4.0.6 on 2022-09-09 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_list_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.auction_list'),
        ),
        migrations.AddField(
            model_name='comments',
            name='message',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
