# Generated by Django 4.0.6 on 2022-09-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_juffa_delete_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='juffa',
            new_name='comments',
        ),
    ]
