# Generated by Django 4.0.6 on 2022-09-13 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_bid_alter_auction_list_price_delete_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_list',
            name='price',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='given_bid', to='auctions.bid'),
        ),
    ]
